/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"STD_TYPES.h"
#include"BIT_MATH.h"
#include"RCC_interface.h"

#include"SYSTICK_interface.h"
#include"GPIO_interface.h"
#include"LEDMRX_interface.h"
u8 DataArray[] ={0,0,252,8,16,8,252,0,0
				,0,0,96,144,96,0,0
				,0,252,16,16,252,0,0,
				124,18,18,124,0,0,
				252,8,16,8,252,0,0,
				248,168,168,0,0,
				248,136,112,0,0};

int main(void)
{

	RCC_voidInitSysClock();
	RCC_voidEnableClock(RCC_APB2, 2);
	RCC_voidEnableClock(RCC_APB2, 3);
	MSTK_voidInit();
	HLEDMRX_voidInit();
	//		LEDMRX_voidShift(DataArray);

	while(1){

		LEDMRX_voidDisplay(DataArray);
		LEDMRX_voidShift(DataArray);

	}
}
